create table if not exists public.child_profiles (
    id bigint generated by default as identity primary key,
    user_email text not null,
    child_name text not null,
    age_band text,
    story_goal text,
    favorite_hero text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists child_profiles_user_email_idx
    on public.child_profiles (user_email);

create index if not exists child_profiles_user_email_name_idx
    on public.child_profiles (user_email, child_name);
